Nuxia\MailStorageBundle\Entity\AbstractMailEntry:
    type: "mappedSuperclass"
    fields:
        object:
            type: "string"
            length: "32"
            nullable: true
        objectId:
            type: "integer"
            nullable: true
            column: "object_id"
        reference:
            type: "string"
            length: "255"
        language:
            type: "string"
            length: "32"
        header:
            type: "text"
            nullable: true
        from:
            type: "simple_array"
            column: "sender"
        to:
            type: "simple_array"
            column: "recipient_to"
        cc:
            type: "simple_array"
            nullable: true
            column: "recipient_cc"
        bcc:
            type: "simple_array"
            nullable: true
            column: "recipient_bcc"
        subject:
            type: "string"
            length: "255"
        content:
            type: "text"
        contentText:
            type: "text"
            column: "content_text"
        status:
            type: "string"
            length: "32"
        createdAt:
            type: "datetime"
            column: "created_at"
        sentAt:
            type: "datetime"
            column: "sent_at"
            nullable: true
    lifecycleCallbacks: {  }
