services:
    nuxia.mail_storage.doctrine.object_manager:
        class:  "Doctrine\ORM\EntityManager"
        public: false
        factory_service: "doctrine"
        factory_method: "getManager"

    nuxia.mail_storage.mail_entry.repository:
        class: "Doctrine\ORM\EntityRepository"
        factory_service: "nuxia.mail_storage.doctrine.object_manager"
        factory_method: "getRepository"
        arguments:
            - "%nuxia.mail_storage.mail_entry.class%"
